### ISSUE TITLE
Improve the error when getting a 500 which is not an Oops error

### ISSUE THREAD

**Issue by adamtheturtle** [VWS-Python/vws-cli#315]
```
$ vws add-target \
    --name foobarbaza \
    --image ~/Documents/personal/vws-test-fixtures/src/vws_test_fixtures/high_quality_image.jpg \
    --base-vws-url http://bbc.co.uk \
    --width 1 \
    --server-access-key a \
    --server-secret-key a
```

(note the URL is the BBC)

```
Traceback (most recent call last):
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/vws/vws.py", line 168, in _make_req
uest
    result_code = response.json()['result_code']
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/requests/models.py", line 898, in j
son
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.p
y", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py
", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py
", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.virtualenvs/vws-cli/bin/vws", line 33, in <module>
    sys.exit(load_entry_point('VWS-CLI', 'console_scripts', 'vws')())
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/click/core.py", line 829, in __call
__
    return self.main(*args, **kwargs)
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/click/core.py", line 1259, in invok
e
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/click/core.py", line 1066, in invok
e
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/adam/Documents/repositories/personal/vws-cli/src/vws_cli/commands.py", line 67, in handle
_vws_exceptions
    wrapped(*args, **kwargs)
  File "/Users/adam/Documents/repositories/personal/vws-cli/src/vws_cli/commands.py", line 384, in add_t
arget
    target_id = vws_client.add_target(
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/vws/vws.py", line 264, in add_targe
t
    response = self._make_request(
  File "/Users/adam/.virtualenvs/vws-cli/lib/python3.8/site-packages/vws/vws.py", line 170, in _make_req
uest
    assert 'Oops' in response.text
AssertionError
```

**Comment by adamtheturtle** [comment]
As of #397 only the JSONDecodeError is shown, not the AssertionError. We also don't handle other errors with bad URLs such as not including a schema. Closing for now, but we may re-open.
